import OpenAI from 'openai';

const openRouterKey = process.env.OPENROUTER_API_KEY;

export class GeminiService {
  static async scoreSpeaking(transcript: string, prompt?: string) {
    if (!transcript || transcript.trim().length === 0) {
      throw new Error("Transcript is empty");
    }

    const systemPrompt = `You are an expert IELTS examiner. You are evaluating a student's speaking response based on the transcribed text.
${prompt ? `The examiner's question was: "${prompt}"` : ''}

CRITICAL RULES:
1. STRICT PROMPT ALIGNMENT: You MUST check if the student's answer is relevant to the question ("${prompt}"). If the answer is completely off-topic or fails to address the core of the question, penalize Task Response / Fluency heavily (Max score 4.0).
2. EMPTY/NOISE PENALTY: If the transcript contains ONLY hesitation markers (e.g., "um", "uh"), is under 3 words, or contains "[SILENCE]", you MUST score EXACTLY 0.0 for ALL criteria and explain that no audio was detected.
3. BAND 1.0 PENALTY: If the transcript has 3 to 10 words but forms no coherent meaning, score EXACTLY 1.0 for ALL criteria.
4. NO HALLUCINATION: You are evaluating ONLY the provided text. Do not assume or invent content that is not in the transcript.
5. STT TOLERANCE: The transcript is generated by AI Speech-to-Text. It may contain minor typos, weird punctuations, or misheard words. Focus on the overall meaning, fluency, and vocabulary used by the student. Be fair and forgiving of obvious transcription errors.

Please evaluate the student's response strictly on the following 4 IELTS speaking criteria:
1. Fluency and Coherence (0.0 - 9.0)
2. Lexical Resource (0.0 - 9.0)
3. Grammatical Range and Accuracy (0.0 - 9.0)
4. Pronunciation (0.0 - 9.0) - Estimate based on typical errors matching the grammar/lexical level.

You must return the result STRICTLY as a valid JSON object without any markdown wrapping (no \`\`\`json) matching this exact schema, AND ALL FEEDBACK TEXT MUST BE IN VIETNAMESE (TẤT CẢ PHẢN HỒI BẰNG TIẾNG VIỆT):
{
  "fluencyCoherence": number,
  "lexicalResource": number,
  "grammarAccuracy": number,
  "pronunciation": number,
  "bandScore": number,
  "aiFeedback": {
    "fluencyCoherence": "feedback string",
    "lexicalResource": "feedback string",
    "grammarAccuracy": "feedback string",
    "pronunciation": "feedback string",
    "general": "overall summary feedback"
  }
}
Note: bandScore should be the average of the 4 criteria rounded to the nearest 0.5.
`;

    try {
      if (!openRouterKey) {
         throw new Error("No OPENROUTER_API_KEY provided");
      }
      
      const openai = new OpenAI({
        baseURL: "https://openrouter.ai/api/v1",
        apiKey: openRouterKey,
      });

      const response = await openai.chat.completions.create({
        model: "openai/gpt-4o-mini",
        response_format: { type: "json_object" },
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `Student Transcript:\n${transcript}` }
        ]
      });

      let text = response.choices[0]?.message?.content || "";
      text = text.replace(/```json/g, '').replace(/```/g, '').trim();

      let parsedData;
      try {
        parsedData = JSON.parse(text);
      } catch (parseError) {
        console.error("[Gemini API] Failed to parse JSON. Raw text was:", text);
        throw parseError;
      }
      return parsedData;
    } catch (error) {
      console.error("[Gemini API] Error scoring speaking response:", error);
      throw new Error("Failed to score speaking response");
    }
  }

  static async scoreWriting(essayText: string, prompt: string) {
    if (!essayText || essayText.trim().length === 0) {
      throw new Error("Essay text is empty");
    }

    const systemPrompt = `You are an expert IELTS Writing examiner. You are evaluating a student's essay response based on the prompt.
The writing prompt/task was: "${prompt}"

CRITICAL RULES:
1. STRICT PROMPT ALIGNMENT: You MUST check if the student's essay directly answers the specific prompt. If the essay is completely off-topic or uses a memorized template that doesn't fit the prompt, score Task Achievement as 0.0 or 1.0.
2. EMPTY/GARBAGE PENALTY: If the essay is under 15 words or just random characters, score EXACTLY 0.0 for ALL criteria.
3. BAND 1.0 PENALTY: If the essay has 15 to 30 words but forms no coherent meaning, score EXACTLY 1.0 for ALL criteria.
4. NO HALLUCINATION: You are evaluating ONLY the provided text. Do not invent or assume content.

Please evaluate the student's response strictly on the following 4 IELTS writing criteria:
1. Task Achievement / Task Response (0.0 - 9.0)
2. Coherence and Cohesion (0.0 - 9.0)
3. Lexical Resource (0.0 - 9.0)
4. Grammatical Range and Accuracy (0.0 - 9.0)

You must return the result STRICTLY as a valid JSON object without any markdown wrapping (no \`\`\`json) matching this exact schema, AND ALL FEEDBACK TEXT MUST BE IN VIETNAMESE (TẤT CẢ PHẢN HỒI BẰNG TIẾNG VIỆT):
{
  "taskAchievement": number,
  "coherenceCohesion": number,
  "lexicalResource": number,
  "grammarAccuracy": number,
  "bandScore": number,
  "aiFeedback": {
    "taskAchievement": "detailed feedback string",
    "coherenceCohesion": "detailed feedback string",
    "lexicalResource": "detailed feedback string",
    "grammarAccuracy": "detailed feedback string",
    "general": "overall summary feedback and tips for improvement"
  }
}
Note: bandScore should be the average of the 4 criteria rounded to the nearest 0.5.
`;

    try {
      if (!openRouterKey) {
         throw new Error("No OPENROUTER_API_KEY provided");
      }
      
      const openai = new OpenAI({
        baseURL: "https://openrouter.ai/api/v1",
        apiKey: openRouterKey,
      });

      const response = await openai.chat.completions.create({
        model: "openai/gpt-4o-mini",
        response_format: { type: "json_object" },
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `Student Essay:\n${essayText}` }
        ]
      });

      let text = response.choices[0]?.message?.content || "";
      text = text.replace(/```json/g, '').replace(/```/g, '').trim();

      let parsedData;
      try {
        parsedData = JSON.parse(text);
      } catch (parseError) {
        console.error("[Gemini API] Failed to parse JSON. Raw text was:", text);
        throw parseError;
      }
      return parsedData;
    } catch (error) {
      console.error("[Gemini API] Error scoring writing response:", error);
      throw new Error("Failed to score writing response");
    }
  }
}
